name: Java CI with Maven
on:
  push:
    branches:
     - 'main'

jobs:
  build-auth-service:
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      env:
        SUPER_SECRET: ${{ secrets.JWT_SECRET }}
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build Auth Service with Maven
      run: |
        cd authusers
        mvn -B package -DJWT_SECRET="$SUPER_SECRET"
  
  build-notifications:
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      env:
        SUPER_SECRET: ${{ secrets.JWT_SECRET }}
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build Notification with Maven
      run: |
        cd notifications
        mvn -B package -DJWT_SECRET="$SUPER_SECRET"
      
  build-todolist:
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      env:
        SUPER_SECRET: ${{ secrets.JWT_SECRET }}
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build TodoList with Maven
      run: |
        cd todolist
        mvn -B package -DJWT_SECRET="$SUPER_SECRET"
